# Generated by Django 4.1.5 on 2023-04-23 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_address_category_order_package_product_useraccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='package',
            name='warehouse',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='Package',
        ),
        migrations.DeleteModel(
            name='Warehouse',
        ),
    ]
