# Generated by Django 4.1.5 on 2023-04-23 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_warehouse_address_x_alter_warehouse_address_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='truck_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
