# Generated by Django 4.1.5 on 2023-04-23 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_package_truck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='truck_id',
            field=models.IntegerField(default=-1),
        ),
    ]
