# Generated by Django 4.1.5 on 2023-04-24 01:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_warehouse_total_shoppingcart'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='address_x',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='address_y',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='shoppingcart',
            name='warehouse',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shoppingcart', to='users.warehouse'),
        ),
    ]
