# Generated by Django 4.1.5 on 2023-04-27 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_warehousestock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='ups_username',
        ),
        migrations.RemoveField(
            model_name='useraccount',
            name='ups_username',
        ),
        migrations.AddField(
            model_name='package',
            name='ups_id',
            field=models.BigIntegerField(default=-1),
        ),
    ]
