# Generated by Django 4.1.5 on 2023-04-28 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_remove_package_ups_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shoppingcart',
            name='ups_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='package',
            name='status',
            field=models.CharField(default='PROCESSING', max_length=50),
        ),
    ]
